### ISSUE TITLE
Dependencies Issue - from graph import driver (clean_graph.py )

### ISSUE THREAD

**Issue by roy2392** [YotamAflalo/chyper-graphRAG-with-langchain-and-neo4j#1]
Hi,
on the file : clean_graph.py you imported the following: 
```from graph import driver```
I looked on the requirements.txt file : 

```
langchain==0.2.12
langchain_anthropic==0.1.22
langchain_community==0.2.10
langchain_core==0.2.27
langchain_experimental==0.0.63
langchain_openai==0.1.20
openai==1.37.2
PyPDF2==3.0.1
streamlit==1.35.0
```

which library is the one you imported graph from ?

**Comment by YotamAflalo** [comment]
its from graph.py (another py file, not a diffrent library), i will make it clearer, thanks!
